name: Release

on:
  workflow_dispatch:

jobs:

  TAGGING:
    runs-on: macos-13
    environment: Tag
    outputs:
      output1: ${{ steps.tagging.outputs.tag }}
        
    steps:
      - uses: actions/checkout@v4
        
      - name: Switching Podspec to release mode
        run: |
          sh .github/release_mode.sh
            
      - id: tagging
        name: Add git tag
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} sh .github/tag.sh
          
  PODS_PUSH:
    runs-on: macos-13
    environment: CocoaPods
    needs: TAGGING

    steps:
    - uses: actions/checkout@v4
    - run: git pull

    - name: Updating Cocoapods
      run: gem install cocoapods
    
    - name: Updating CocoaPods repo
      run: pod repo update
      
    - name: CocoaPods push
      run: |
        PODS_USER=${{ secrets.PODS_USER }} PODS_PASS=${{ secrets.PODS_PASS }} sh .github/cocoapods_publish.sh
    
    - name: Prepare release notes
      run: |
        sh .github/release_notes.sh
    
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{needs.TAGGING.outputs.output1}}
        bodyFile: ".github/release_notes_template.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
